=== EltonQuekMK/SanctionedListsApp/data/jsonschema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "TYPE": {
                "type": "string",
                "enum": [
                    "individual",
                    "entity"
                ]
            },
            "FIRST_NAME": {
                "type": "string"
            },
            "SECOND_NAME": {
                "type": "string"
            },
            "THIRD_NAME": {
                "type": "string"
            },
            "ALIAS": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "ALIAS_NAME": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "ALIAS_NAME"
                    ]
                }
            },
            "ADDRESS": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "DATE_OF_BIRTH": {
                "type": "string"
            },
            "PLACE_OF_BIRTH": {
                "type": "object",
                "properties": {
                    "COUNTRY": {
                        "type": "string"
                    },
                    "CITY": {
                        "type": "string"
                    },
                    "STATE_PROVINCE": {
                        "type": "string"
                    }
                }
            },
            "NAME_ORIGINAL_SCRIPT": {
                "type": "string"
            },
            "TITLE": {
                "type": "string"
            },
            "DESIGNATION": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "NATIONALITY": {
                "type": "string"
            },
            "COMMENTS": {
                "type": "string"
            }
        },
        "required": [
            "TYPE",
            "FIRST_NAME"
        ]
    }
}

=== EltonQuekMK/SanctionedListsApp/data/un_south_sudan.json
[
  {
    "TYPE": "individual",
    "FIRST_NAME": "GABRIEL",
    "SECOND_NAME": "JOK RIAK",
    "THIRD_NAME": "MAKOL",
    "ALIAS": [
      {
        "ALIAS_NAME": "Gabriel Jok"
      },
      {
        "ALIAS_NAME": "Jok Riak"
      },
      {
        "ALIAS_NAME": "Jock Riak"
      }
    ],
    "ADDRESS": [
      "South Sudan",
      "Wau, South Sudan"
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "Bor",
      "COUNTRY": "Sudan"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "Lieutenant General",
    "DESIGNATION": [
      "Former Sudan People’s Liberation Army’s (SPLA) Sector One\nCommander",
      "Chief of Defence Forces"
    ],
    "NATIONALITY": "South Sudan",
    "COMMENTS": "Appointed as Chief of Defence Forces on 2 May 2018. Commanded SPLA Sector One, which operates primarily within Unity State, since January 2013. In his position as the SPLA Sector One commander, he has expanded or extended the conflict in South Sudan through breaches of the Cessation of Hostilities Agreement. The SPLA is a South Sudanese military entity that has engaged in actions that have extended the conflict in South Sudan, including breaches of the January 2014 Cessation of Hostilities Agreement and the May 9, 2014 Agreement to Resolve the Crisis in South Sudan, which was a re-commitment to the CoHA and has obstructed the activities of IGAD’s Monitoring and Verification Mechanism.  INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "SIMON",
    "SECOND_NAME": "GATWECH",
    "THIRD_NAME": "DUAL",
    "ALIAS": [
      {
        "ALIAS_NAME": "Simon Gatwich Dual"
      },
      {
        "ALIAS_NAME": "Simon Getwech Dual"
      },
      {
        "ALIAS_NAME": "Simon Gatwec Duel"
      },
      {
        "ALIAS_NAME": "Simon Gatweach"
      },
      {
        "ALIAS_NAME": "Simon Gatwick"
      },
      {
        "ALIAS_NAME": "Simon Gatwech"
      },
      {
        "ALIAS_NAME": "Simon Garwich"
      },
      {
        "ALIAS_NAME": "General Gaduel"
      },
      {
        "ALIAS_NAME": "Dhual"
      }
    ],
    "ADDRESS": [
      "Sudan",
      "South Sudan"
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "Akobo, Jonglei State",
      "COUNTRY": "Sudan"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "Major General",
    "DESIGNATION": [
      "Chief of General Staff, SPLA in Opposition"
    ],
    "NATIONALITY": "",
    "COMMENTS": "Is the SPLM-IO Chief of General Staff and was previously the commander of\nopposition forces in Jonglei State. His forces conducted an early February 2015 attack\nin Jonglei State, and as of March 2015, he had tried to destroy the peace in Jonglei\nState through attacks on the civilian population. Photograph available for inclusion in the INTERPOL-UN Security Council Special Notice.  INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "JAMES",
    "SECOND_NAME": "KOANG",
    "THIRD_NAME": "CHUOL",
    "ALIAS": [
      {
        "ALIAS_NAME": "James Koang Chol Ranley"
      },
      {
        "ALIAS_NAME": "James Koang Chol"
      },
      {
        "ALIAS_NAME": "Koang Chuol Ranley"
      },
      {
        "ALIAS_NAME": "James Koang Chual"
      }
    ],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "COUNTRY": ""
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "Major General",
    "DESIGNATION": [
      ""
    ],
    "NATIONALITY": "South Sudan",
    "COMMENTS": "Appointed commander of the Sudan People’s Liberation Army in Opposition\n(SPLA-IO) Special Division in December 2014. His forces have been engaged in attacks\nagainst civilians. In February 2014, forces under his command attacked United Nations\ncamps, hospitals, churches, and schools, engaging in widespread rape, torture, and the\ndestruction of property, in an attempt to flush out civilians, soldiers, and policemen\nallied with the government. INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "SANTINO",
    "SECOND_NAME": "DENG",
    "THIRD_NAME": "WOL",
    "ALIAS": [
      {
        "ALIAS_NAME": "Santino Deng Wuol"
      },
      {
        "ALIAS_NAME": "Santino Deng Kuol"
      }
    ],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "Aweil",
      "COUNTRY": "Sudan"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "Major General",
    "DESIGNATION": [
      "Commander of the SPLA’s Third Division"
    ],
    "NATIONALITY": "",
    "COMMENTS": "Has led and directed military actions against opposition forces and\nconducted confrontational troop movements in violation of the CoHA. During May 2015,\nforces under his command killed children, women and old men, burned property, and stole\nlivestock as they advanced through Unity State towards Thorjath oil field. INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "MARIAL",
    "SECOND_NAME": "CHANUONG",
    "THIRD_NAME": "YOL",
    "ALIAS": [
      {
        "ALIAS_NAME": "Marial Chinuong"
      },
      {
        "ALIAS_NAME": "Marial Chan"
      },
      {
        "ALIAS_NAME": "Marial Chanoung Yol"
      },
      {
        "ALIAS_NAME": "Marial Chinoum"
      }
    ],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "COUNTRY": ""
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "",
    "DESIGNATION": [
      "Sudan People’s Liberation Army Major General",
      "Commander, Presidential Guard Unit"
    ],
    "NATIONALITY": "South Sudan",
    "COMMENTS": "His Presidential Guard led the slaughter of Nuer civilians in and around\nJuba, many who were buried in mass graves. One such grave was purported to contain\n200-300 civilians. INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "PETER",
    "SECOND_NAME": "GADET",
    "THIRD_NAME": "",
    "ALIAS": [
      {
        "ALIAS_NAME": "Peter Gatdet Yaka"
      },
      {
        "ALIAS_NAME": "Peter Gadet Yak"
      },
      {
        "ALIAS_NAME": "Peter Gadet Yaak"
      },
      {
        "ALIAS_NAME": "Peter Gatdet Yaak"
      },
      {
        "ALIAS_NAME": "Peter Gatdet"
      },
      {
        "ALIAS_NAME": "Peter Gatdeet Yaka"
      }
    ],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "COUNTRY": ""
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "General, Major General",
    "DESIGNATION": [
      ""
    ],
    "NATIONALITY": "",
    "COMMENTS": "Appointed the SPLA-IO’s Deputy Chief of Staff for Operations on December\n21, 2014. Forces under his command targeted civilians, including women, in April 2014\nduring an assault on Bentiu, including targeted killings on the basis of\nethnicity. INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "MALEK",
    "SECOND_NAME": "REUBEN",
    "THIRD_NAME": "RIAK",
    "ALIAS": [],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "Yei",
      "COUNTRY": "South Sudan"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "Lieutenant General",
    "DESIGNATION": [
      "Deputy Chief of General Staff for Logistics",
      "Deputy Chief of Defence Staff and Inspector General of the Army"
    ],
    "NATIONALITY": "South Sudan",
    "COMMENTS": "As SPLA Deputy Chief of Staff for Logistics, Riak was one of the senior officials of the Government of South Sudan who planned and oversaw an offensive in Unity state in 2015 that resulted in widespread destruction and large population displacement."
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "PAUL",
    "SECOND_NAME": "MALONG",
    "THIRD_NAME": "AWAN",
    "ALIAS": [
      {
        "ALIAS_NAME": "Paul Malong Awan Anei"
      },
      {
        "ALIAS_NAME": "Paul Malong"
      },
      {
        "ALIAS_NAME": "Bol Malong"
      }
    ],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "Malualkon",
      "COUNTRY": "South Sudan"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "General",
    "DESIGNATION": [
      "Former Chief of Staff of the Sudan People’s Liberation Army (SPLA)",
      "Former Governor, Northern Bahr el-Ghazal State"
    ],
    "NATIONALITY": "South Sudan, Uganda",
    "COMMENTS": "As Chief of General Staff of the SPLA, Malong expanded or extended the conflict in South Sudan through breaches of the Cessation of Hostilities Agreement and breaches of the 2015 Agreement on the Resolution of the Conflict in South Sudan (ARCSS). He reportedly directed efforts to kill opposition leader Riek Machar. He ordered SPLA units to prevent the transport of humanitarian supplies. Under Malong’s leadership, the SPLA attacked civilians, schools and hospitals; forced the displacement of civilians; carried out enforced disappearances; arbitrarily detained civilians; and conducted acts of torture, and rape. He mobilized the Mathiang Anyoor Dinka tribal militia, which uses child soldiers. Under his leadership, the SPLA restricted UNMISS, the Joint Monitoring and Evaluation Commission (JMEC), and CTSAMM access to sites to investigate and document abuses."
  }
]

=== EltonQuekMK/SanctionedListsApp/data/un_sudan.json
[
  {
    "TYPE": "individual",
    "FIRST_NAME": "GAFFAR",
    "SECOND_NAME": "MOHAMMED",
    "THIRD_NAME": "ELHASSAN",
    "ALIAS": [],
    "ADDRESS": [
      "El Waha, Omdurman, Sudan"
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "COUNTRY": ""
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "",
    "DESIGNATION": [
      "Major-General and Commander of the Western Military Region for the\nSudanese Armed Forces (SAF)"
    ],
    "NATIONALITY": "na",
    "COMMENTS": "Retired from the Sudanese Army. INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "MUSA",
    "SECOND_NAME": "HILAL",
    "THIRD_NAME": "ABDALLA",
    "ALIAS": [
      {
        "ALIAS_NAME": "(Sheikh) Musa Hilal"
      },
      {
        "ALIAS_NAME": "Abd Allah"
      },
      {
        "ALIAS_NAME": "Abdallah"
      },
      {
        "ALIAS_NAME": "AlNasim"
      },
      {
        "ALIAS_NAME": "Al Nasim"
      },
      {
        "ALIAS_NAME": "AlNaseem"
      },
      {
        "ALIAS_NAME": "Al Naseem"
      },
      {
        "ALIAS_NAME": "AlNasseem"
      },
      {
        "ALIAS_NAME": "Al Nasseem"
      }
    ],
    "ADDRESS": [
      "Kabkabiya, Sudan",
      "Resides in Kabkabiya and the city of Kutum, Northern Darfur and has resided in Khartoum., Kutum, Sudan"
    ],
    "DATE_OF_BIRTH": "1964-01-01",
    "PLACE_OF_BIRTH": {
      "COUNTRY": ""
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "",
    "DESIGNATION": [
      "formerly Member of the National Assembly of Sudan from Al-Waha district",
      "formerly special adviser to the Ministry of Federal Affairs",
      "Paramount Chief of the Mahamid Tribe in North Darfur"
    ],
    "NATIONALITY": "Sudan",
    "COMMENTS": "Photo available for inclusion in the INTERPOL-UN Security Council Special Notice.  INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "JIBRIL",
    "SECOND_NAME": "ABDULKARIM",
    "THIRD_NAME": "IBRAHIM",
    "ALIAS": [
      {
        "ALIAS_NAME": "General Gibril Abdul Kareem Barey"
      },
      {
        "ALIAS_NAME": "“Tek”"
      },
      {
        "ALIAS_NAME": "Gabril Abdul Kareem Badri"
      }
    ],
    "ADDRESS": [
      "Resides in Tine, on the Sudanese side of the border with Chad, Tine, Sudan"
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "El-Fasher",
      "STATE_PROVINCE": "North Darfur",
      "NOTE": "Place of Birth: Nile District, El-Fasher, El- Fasher, North Darfur"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "",
    "DESIGNATION": [
      "National Movement for Reform and Development (NMRD) Field\nCommander"
    ],
    "NATIONALITY": "Sudan, South Sudan",
    "COMMENTS": "Photo available for inclusion in the INTERPOL-UN Security Council Special Notice.  INTERPOL-UN Security Council Special Notice web link:https://www.interpol.int/en/How-we-work/Notices/View-UN-Notices-Individuals"
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "ABDEL",
    "SECOND_NAME": "RAHMAN",
    "THIRD_NAME": "JUMA",
    "ALIAS": [],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "Bahr Elarab",
      "STATE_PROVINCE": "East Darfur",
      "COUNTRY": "Sudan"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "",
    "DESIGNATION": [
      "Rapid Support Forces (RSF) Major General and West Darfur Commander"
    ],
    "NATIONALITY": "Sudan",
    "COMMENTS": "Gender: Male."
  },
  {
    "TYPE": "individual",
    "FIRST_NAME": "OSMAN",
    "SECOND_NAME": "MOHAMED",
    "THIRD_NAME": "HAMID",
    "ALIAS": [],
    "ADDRESS": [
      ""
    ],
    "DATE_OF_BIRTH": "",
    "PLACE_OF_BIRTH": {
      "CITY": "Kadiqali",
      "STATE_PROVINCE": "South Darfur",
      "COUNTRY": "Sudan"
    },
    "NAME_ORIGINAL_SCRIPT": "",
    "TITLE": "",
    "DESIGNATION": [
      "Rapid Support Forces (RSF) Major General and Head of RSF Operations"
    ],
    "NATIONALITY": "Sudan",
    "COMMENTS": "Gender: Male."
  }
]
